name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust this to your project's Node.js version

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8  # Adjust this to your pnpm version

      - name: Install dependencies
        run: pnpm install
        working-directory: ./docs

      - name: Build documentation
        run: pnpm build
        working-directory: ./docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs/doc_build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
